### PR TITLE
updating our info 

### PR DESCRIPTION
**Pull request by pelsasser**

### CODE REVIEW

**Comment by evbots** [comment]
Hey @pelsasser thanks for the PR. Are the derivatives represented by an Ethereum standard like ERC20?

**Comment by pelsasser** [comment]
They are not.  You can use any ERC20 as collateral but the resulting position of a trade is not an ERC20 due to its tie to a collateral pool.

**Comment by evbots** [comment]
Ok, i will merge for now and look into more later.

**Comment by pelsasser** [comment]
Thanks Evan!

**Pull request merged**
