### PR TITLE
Add Aqueduct Protocol

### PR DESCRIPTION
**Pull request by eliooses**
For further info please checkout: https://medium.com/ercdex/introducing-aqueduct-tools-for-liquidity-sharing-and-automated-trading-45726a0e20ab

### CODE REVIEW

**Comment by evbots** [comment]
Hey @eliooses, I don't think this is a protocol in the sense that this list is about. It seems to me that Aqueduct is a set of libraries that allow you to connect and exchange data with 0x relayers. Meaning, it doesn't look like it's implemented as a smart contract or code on the blockchain.

**Comment by eliooses** [comment]
I have my doubts. That's why I always link the official docs.

But as far as I understand, it is a protocol, although in a more abstract layer and underlying the exchange protocol (in this case, 0x protocol). Of course, I leave it to your entire criteria. 

If you want, I can write to the devs to answer these questions.

**Comment by evbots** [comment]
Ok, yeah it just seems like it's a set of libraries, that at it's core, uses the 0x protocol. Let me see if I can get the github handle of one of the devs to clarify.

**Comment by evbots** [comment]
Hi @lukeautry and @aktary, is this a protocol implemented on the blockchain, or just a set of libraries that relies on 0x relays?

**Comment by lukeautry** [comment]
With the current set of features, there are no additional smart contracts for Aqueduct - we're just relying on the 0x protocol and their Exchange contract.

In the future, we'll be providing additional rules and schemas around liquidity sharing/fee sharing. Some of these rules will be codified/enforced through our own smart contracts and payment channels. Some examples of what this will look like:
- Smart contract and/or payment channel that controls payout of fee sharing dividends
- Smart contract that controls which entities are allowed to participate in the system (KYC whitelisting)

In any case, I'm not sure if Aqueduct belongs on this list. Aqueduct, if it can be considered a protocol, is a set of tools around interacting with the 0x ecosystem of relayers. It is not a decentralized exchange protocol unto itself.

**Comment by evbots** [comment]
thanks @lukeautry for the clarification

**Comment by eliooses** [comment]
I do not share the criteria, but it is fine for me. I just forked.

I think then @lukeautry should change the text on the homepage of your website:

> A protocol and tool set for sharing global, decentralized liquidity on the Ethereum network, built by ERC dEX.

To:

> A tool set for sharing global, decentralized liquidity on the Ethereum network, built by ERC dEX.

Best regards.

**Comment by evbots** [comment]
Agreed, the description is slightly confusing

**Comment by aktary** [comment]
The reason we have the word “protocol” in there is because the next two version will actually involve a protocol to facilitate the payments functionality.

**Pull request closed without merging**
