### PR TITLE
Blocknet Protocol

### PR DESCRIPTION
**Pull request by little-eagle**
Please add the Blocknet Protocol. Great source, thanks.

### CODE REVIEW

**Comment by evbots** [comment]
hey @little-eagle this is the first I am hearing of this project. Do you use or contribute to blocknet?

**Comment by little-eagle** [comment]
The project has been around since 2014 but really gained steam early this year.

I'm not a team member but I created a website (https://blockdx.co/) to show the live orders of Block DX, which is a DEX built on the protocol.

Is it ok to add the protocol to your list? Seems an ideal candidate?

**Comment by little-eagle** [comment]
@evbots You may also want to check out https://api.blocknet.co/

**Comment by little-eagle** [comment]
@evbots That is a fair description. I've removed it. Thanks!

**Comment by evbots** [comment]
@little-eagle thanks for the contribution :-)

**Pull request merged**
